version: '3'

services:
  nginx:
    image: nginx:latest
    ports:
      - "${INTERFACE}:80:80"
      - "${INTERFACE}:443:443"
    volumes:
      - ./www:${SITE_PATH}
      - ./hosts:/etc/nginx/conf.d
    links:
      - php
    networks:
      - docker_network

  php:
    build: ./images/php
    volumes:
      - ./www:${SITE_PATH}
    links:
      - mysql
    networks:
      - docker_network

  mysql:
    image: mysql:${MYSQL_VERSION}
    ports:
        - "${INTERFACE}:3306:3306"
    volumes:
        - ./mysql:/var/lib/mysql
    # задаем пароль для root пользователя
    environment:
        - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
        - MYSQL_DATABASE=${MYSQL_DATABASE}
        - MYSQL_USER=${MYSQL_USER}
        - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    networks:
        - docker_network
networks:
    docker_network:
        driver: bridge
        ipam:
            driver: default
            config:
                - subnet: 10.100.0.0/24