version: '3'

services:
  nginx:
    image: nginx:latest
    ports:
      - 80:80
      - "443:443"
    volumes:
      - ./www:/var/www
      - ./hosts:/etc/nginx/conf.d
    links:
      - php

  php:
    build: ./images/php
    volumes:
      - ./www:/var/www
    links:
      - mysql

  mysql:
    image: mysql:8
    ports:
        - "3306:3306"
    volumes:
        - ./mysql:/var/lib/mysql
    # задаем пароль для root пользователя
    environment:
        - MYSQL_ROOT_PASSWORD=123456
        - MYSQL_DATABASE=docker
        - MYSQL_USER=user
        - MYSQL_PASSWORD=secret